# Generated by Django 4.0.3 on 2022-03-18 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admins',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sold_product',
        ),
        migrations.AddField(
            model_name='sales',
            name='sold_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.products'),
        ),
    ]
