# Generated by Django 4.0.3 on 2022-03-18 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_admins_options_remove_sales_sold_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sold_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.products'),
        ),
    ]
