# Generated by Django 4.0.3 on 2022-03-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_sales_sold_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
