# Generated by Django 4.0.3 on 2022-03-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='admin_key',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
