# Generated by Django 4.0.3 on 2022-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_admins_admin_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='admin_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
