# Generated by Django 4.0.3 on 2022-03-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_admins_admin_key_alter_admins_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='item_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
