# Generated by Django 4.0.3 on 2022-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_products_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
