# Generated by Django 4.0.3 on 2022-03-24 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='chipottle-api/products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='item_image',
            field=models.ImageField(upload_to='chipottle-api/products'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 22, 59, 35, 161016)),
        ),
    ]
