# Generated by Django 4.0 on 2022-03-24 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_events_event_image_alter_products_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 15, 53, 42, 735252)),
        ),
    ]
